### ISSUE TITLE
PA Review: Stories

### ISSUE THREAD

**Issue by kxwzhang** [kxwzhang/Median#3]
###  Functionality
- [x] Loads the Feed with title, subtitle, author and images displayed
   - [x] Feed displays randomized stories upon each render
   - [x] Feed's "Editor's Picks" Properly sends user to a random story
- [x] Can click on either image or text to link to that particular story
- [x] Can hover profile to bring a drop down to create a new story or view a list of authored stories.
- [x] On the "Your Stories" page, can edit or delete stories. 
   - [x] Can also click on text to visit the story show page
   - [x] Properly re-renders upon delete 
   - [x] Properly re-renders after creating a new story
   - [x] Has a button to create a new story
- [x] Creating a new story allows to add title, subtitle, body and upload an image
   - [x] Can preview the image before publishing
   - [x] Redirects the user to the story show page of the story that was just published

**Comment by Vanchen07** [comment]
- Functionality is great! Loading does takes a little bit of time.
