### ISSUE TITLE
PA Review: Comments

### ISSUE THREAD

**Issue by kxwzhang** [kxwzhang/Median#4]
###  Functionality
- [x] Signed in users can view comments on each story's show page
- [x] Comments can be nested
   - [x] Comments are nested properly and in the correct order
   - [x] Can reply to a parent comment
- [x] Can leave a top level comment
- [x] Current user can delete their own comments
   - [x] Current user cannot delete other users comments

**Comment by Vanchen07** [comment]
- looks good!
